### ISSUE TITLE
Allen and drift datasets are the same...

### ISSUE THREAD

**Issue by yger** [flatironinstitute/neuropixels-data-sep-2020#15]
I downloaded all the datasets, using the download_recording.py script. However, it looks like the two allen dataset are the same (same size and same data...), and same for the drift recordings. The code created separate files, but content are identical

**Comment by magland** [comment]
You're absolutely right. That's embarrassing.... I had a copy and paste error in the prepare script. I just fixed it, reran the prepare script. So if you git pull this repo you should it should be a non-dup now.

Here are the diffs showing the change:
https://github.com/flatironinstitute/neuropixels-data-sep-2020/commit/da8ff1e26767c08758e4f9e1deede9573289e947#diff-14ff3c3b1ba49e0386d4e250f0af7842
https://github.com/flatironinstitute/neuropixels-data-sep-2020/commit/da8ff1e26767c08758e4f9e1deede9573289e947#diff-068b939774db53f90e085cbd43930134

Tagging: @alexmorley @mhhennig
