### ISSUE TITLE
File not found. 

### ISSUE THREAD

**Issue by yger** [flatironinstitute/neuropixels-data-sep-2020#19]
Maybe this is related to the last PR, but I can not download files anymore. kachery-p2p and the website are up to date, kachery deamon is running, but while everything worked smoothly before the weekend, now I always have the same file not found error, irregardless of what I want to download 

Problem is that even the file know_recordings is not found

LoadFileError: Error loading file: File not found.: sha1://e242e4497b8cd0cb29c1df159de16ae6735f1d9e/known_recordings.json

Could it be that there is a path issue somewhere with the sha1 addresses?

**Comment by magland** [comment]
@yger. One of the nodes ran out of disk space. I freed up some space so it should be back up.

I have verified that the known_recordings.json is now on the network.

Please retry.

**Comment by yger** [comment]
Actually, this may be related or not, but I realized that the log file of
my computer (/var/syslog) increased to more than 130Gb. Could it be related
to the activity of the kachery-p2p daemon?

**Comment by magland** [comment]
kachery-p2p does not write to /var/syslog. Not sure what indirect affect it could have.

**Comment by yger** [comment]
No worries, the problem is solved and I was just wondering. I guess it was related to the firewall on the machine (ufw). Thanks!
